
-- Create employees table
CREATE TABLE IF NOT EXISTS employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  role TEXT CHECK (role IN ('worker', 'manager', 'admin')),
  active BOOLEAN DEFAULT true,
  auth_user_id UUID,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create services table
CREATE TABLE IF NOT EXISTS services (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  short_description TEXT,
  description TEXT,
  icon_name TEXT DEFAULT 'Wrench',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add new columns to requests table (mapped to 'quotes')
ALTER TABLE requests ADD COLUMN IF NOT EXISTS inspection_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS due_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS employee_id BIGINT REFERENCES employees(id);
ALTER TABLE requests ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS phone TEXT; -- Check if this exists already
ALTER TABLE requests ADD COLUMN IF NOT EXISTS customer_name TEXT; -- Mapping name to customer_name logic in UI, but maybe keep name?
-- Actually, the requests table already has 'name', 'email', 'message', 'company', 'priority', 'status', 'assigned_to'.
-- We will use 'name' as 'customer_name'.

-- Create quote_notes table
CREATE TABLE IF NOT EXISTS quote_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id BIGINT REFERENCES requests(id) ON DELETE CASCADE,
  author_id UUID NOT NULL, -- Supabase Auth ID
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,
  updated_by UUID
);

-- Create quote_note_edits table (mentioned in code)
CREATE TABLE IF NOT EXISTS quote_note_edits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_id BIGINT REFERENCES quote_notes(id) ON DELETE CASCADE,
  editor_id UUID NOT NULL,
  previous_value TEXT,
  new_value TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create quote_time_entries table
CREATE TABLE IF NOT EXISTS quote_time_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id BIGINT REFERENCES requests(id) ON DELETE CASCADE,
  employee_id BIGINT REFERENCES employees(id),
  hours NUMERIC(10, 2),
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create quote_attachments table
CREATE TABLE IF NOT EXISTS quote_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id BIGINT REFERENCES requests(id) ON DELETE CASCADE,
  file_name TEXT,
  file_path TEXT,
  uploaded_by UUID,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create quote_portal_tokens table
CREATE TABLE IF NOT EXISTS quote_portal_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id BIGINT REFERENCES requests(id) ON DELETE CASCADE,
  token TEXT UNIQUE NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on new tables (simplified for now, assume authenticated users can access admin stuff)
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_note_edits ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_time_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_portal_tokens ENABLE ROW LEVEL SECURITY;

-- Policies (Open for authenticated users for now, refine later)
CREATE POLICY "Enable all access for authenticated users" ON employees FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON services FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON quote_notes FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON quote_note_edits FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON quote_time_entries FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON quote_attachments FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON quote_portal_tokens FOR ALL USING (auth.role() = 'authenticated');

-- Special policy for portal (public read access via token is handled by application logic usually, but if using RLS for public table...)
-- Actually, the portal page fetches via Supabase client. If it's public, we might need a policy for anon if we use anon client.
-- The provided code uses `supabase.from...`, so we need to ensure anon key can read if token is valid.
-- For now, let's just enable read for anon on quote_portal_tokens and quotes/requests if we want public portal to work without auth.
-- BUT, the portal code seems to use `supabase` client which might be authenticated or not.
-- Let's assume public access for portal tokens is needed to validate.

CREATE POLICY "Allow public read on portal tokens" ON quote_portal_tokens FOR SELECT USING (true);

-- Storage bucket for attachments
INSERT INTO storage.buckets (id, name, public)
VALUES ('quote-attachments', 'quote-attachments', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Authenticated can upload attachments"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'quote-attachments');

CREATE POLICY "Public can read attachments"
ON storage.objects FOR SELECT
USING (bucket_id = 'quote-attachments');
