
-- Create employees table (New table, keeping BIGINT for ID is fine)
CREATE TABLE IF NOT EXISTS employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  role TEXT CHECK (role IN ('worker', 'manager', 'admin')),
  active BOOLEAN DEFAULT true,
  auth_user_id UUID,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create services table
CREATE TABLE IF NOT EXISTS services (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  short_description TEXT,
  description TEXT,
  icon_name TEXT DEFAULT 'Wrench',
  sort_order INTEGER DEFAULT 0,
  -- NEW FIELDS FOR LANDING PAGE
  href TEXT,
  features TEXT[], -- Array of strings
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add new columns to requests table
-- requests.id is UUID, so referencing it must be UUID.
ALTER TABLE requests ADD COLUMN IF NOT EXISTS inspection_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS due_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS employee_id BIGINT REFERENCES employees(id);
ALTER TABLE requests ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS customer_name TEXT;

-- Create quote_notes table
CREATE TABLE IF NOT EXISTS quote_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id UUID REFERENCES requests(id) ON DELETE CASCADE, -- CHANGED TO UUID
  author_id UUID NOT NULL,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,
  updated_by UUID
);

-- Create quote_note_edits table
CREATE TABLE IF NOT EXISTS quote_note_edits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_id BIGINT REFERENCES quote_notes(id) ON DELETE CASCADE,
  editor_id UUID NOT NULL,
  previous_value TEXT,
  new_value TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create quote_time_entries table
CREATE TABLE IF NOT EXISTS quote_time_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id UUID REFERENCES requests(id) ON DELETE CASCADE, -- CHANGED TO UUID
  employee_id BIGINT REFERENCES employees(id),
  hours NUMERIC(10, 2),
  rate NUMERIC(10, 2),
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create quote_attachments table
CREATE TABLE IF NOT EXISTS quote_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id UUID REFERENCES requests(id) ON DELETE CASCADE, -- CHANGED TO UUID
  file_name TEXT,
  file_path TEXT,
  uploaded_by UUID,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create quote_portal_tokens table
CREATE TABLE IF NOT EXISTS quote_portal_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id UUID REFERENCES requests(id) ON DELETE CASCADE, -- CHANGED TO UUID
  token TEXT UNIQUE NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create quote_messages table
CREATE TABLE IF NOT EXISTS quote_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id UUID REFERENCES requests(id) ON DELETE CASCADE,
  author_id UUID,
  message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_note_edits ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_time_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_portal_tokens ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable all access for authenticated users" ON employees FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON services FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON quote_notes FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON quote_note_edits FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON quote_time_entries FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON quote_attachments FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON quote_portal_tokens FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow public read on portal tokens" ON quote_portal_tokens FOR SELECT USING (true);

-- NEW: Allow public read access to services for the landing page
CREATE POLICY "Allow public read access" ON services FOR SELECT USING (true);

-- Storage bucket for attachments
INSERT INTO storage.buckets (id, name, public)
VALUES ('quote-attachments', 'quote-attachments', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Authenticated can upload attachments"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'quote-attachments');

CREATE POLICY "Public can read attachments"
ON storage.objects FOR SELECT
USING (bucket_id = 'quote-attachments');

-- If table already exists, add columns (run this part separately or as part of migration)
ALTER TABLE services ADD COLUMN IF NOT EXISTS href TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS features TEXT[];
