-- Project Phoenix CRM flow cleanup
-- Keeps existing requests/services/employees/quote_* tables and adds missing CRM flow tables.

create extension if not exists pgcrypto;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  company_name text,
  organization_number text,
  email text,
  phone text,
  website text,
  address text,
  customer_type text,
  status text not null default 'lead',
  notes text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete cascade,
  name text,
  email text,
  phone text,
  role text,
  is_primary boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete set null,
  contact_id uuid references public.contacts(id) on delete set null,
  source_request_id uuid references public.requests(id) on delete set null,
  title text,
  description text,
  status text not null default 'open',
  value_estimate numeric(12,2),
  source text default 'requests',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.phoenix_ideas (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  category text,
  status text not null default 'parkert',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quotes (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete set null,
  contact_id uuid references public.contacts(id) on delete set null,
  lead_id uuid references public.leads(id) on delete set null,
  source_request_id uuid references public.requests(id) on delete set null,
  title text not null,
  description text,
  status text not null default 'kladd',
  valid_until date,
  total_ex_vat numeric(12,2) not null default 0,
  total_vat numeric(12,2) not null default 0,
  total_inc_vat numeric(12,2) not null default 0,
  internal_notes text,
  customer_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quote_items (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid references public.quotes(id) on delete cascade,
  description text not null,
  quantity numeric(12,2) not null default 1,
  unit_price numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  vat_rate numeric(5,2) not null default 25,
  line_total_ex_vat numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.quote_messages (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid,
  author_id uuid,
  author_name text,
  author_type text default 'customer',
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.quote_tokens (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null,
  token text unique not null,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.quote_portal_tokens (
  id bigint generated by default as identity primary key,
  quote_id uuid not null,
  token text unique not null,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.phoenix_site_content (
  id uuid primary key default gen_random_uuid(),
  key text not null default 'homepage',
  title text,
  content jsonb,
  section text,
  page text default 'home',
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.requests add column if not exists customer_id uuid references public.customers(id) on delete set null;
alter table public.requests add column if not exists contact_id uuid references public.contacts(id) on delete set null;
alter table public.requests add column if not exists lead_id uuid references public.leads(id) on delete set null;
alter table public.requests add column if not exists converted_at timestamptz;
alter table public.requests add column if not exists converted_to_customer boolean not null default false;

create index if not exists idx_contacts_customer_id on public.contacts(customer_id);
create index if not exists idx_leads_customer_id on public.leads(customer_id);
create index if not exists idx_leads_source_request_id on public.leads(source_request_id);
create index if not exists idx_requests_lead_id on public.requests(lead_id);
create index if not exists idx_phoenix_ideas_status on public.phoenix_ideas(status);
create index if not exists idx_quotes_customer_id on public.quotes(customer_id);
create index if not exists idx_quotes_lead_id on public.quotes(lead_id);
create index if not exists idx_quote_items_quote_id on public.quote_items(quote_id);
create index if not exists idx_quote_messages_quote_id on public.quote_messages(quote_id);
create index if not exists idx_quote_tokens_token on public.quote_tokens(token);
create index if not exists idx_quote_portal_tokens_token on public.quote_portal_tokens(token);
create unique index if not exists idx_phoenix_site_content_key_page on public.phoenix_site_content(key, page);

alter table if exists public.quote_messages add column if not exists author_type text default 'customer';
alter table if exists public.quote_messages add column if not exists author_name text;
alter table if exists public.requests add column if not exists portal_status text;
