-- Project Phoenix CRM flow cleanup
-- Keeps existing requests/services/employees/quote_* tables and adds missing CRM flow tables.

create extension if not exists pgcrypto;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  company_name text,
  organization_number text,
  email text,
  phone text,
  website text,
  address text,
  customer_type text,
  status text not null default 'lead',
  notes text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete cascade,
  name text,
  email text,
  phone text,
  role text,
  is_primary boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete set null,
  contact_id uuid references public.contacts(id) on delete set null,
  source_request_id uuid references public.requests(id) on delete set null,
  title text,
  description text,
  status text not null default 'open',
  value_estimate numeric(12,2),
  source text default 'requests',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.phoenix_ideas (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  category text,
  status text not null default 'parkert',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quotes (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete set null,
  contact_id uuid references public.contacts(id) on delete set null,
  lead_id uuid references public.leads(id) on delete set null,
  source_request_id uuid references public.requests(id) on delete set null,
  title text not null,
  description text,
  status text not null default 'kladd',
  valid_until date,
  total_ex_vat numeric(12,2) not null default 0,
  total_vat numeric(12,2) not null default 0,
  total_inc_vat numeric(12,2) not null default 0,
  internal_notes text,
  customer_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quote_items (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid references public.quotes(id) on delete cascade,
  description text not null,
  quantity numeric(12,2) not null default 1,
  unit_price numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  vat_rate numeric(5,2) not null default 25,
  line_total_ex_vat numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.quote_messages (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid,
  author_id uuid,
  author_name text,
  author_type text default 'customer',
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.quote_tokens (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null,
  token text unique not null,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.quote_portal_tokens (
  id bigint generated by default as identity primary key,
  quote_id uuid not null,
  token text unique not null,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.phoenix_site_content (
  id uuid primary key default gen_random_uuid(),
  key text not null default 'homepage',
  title text,
  content jsonb,
  section text,
  page text default 'home',
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Existing CRM tables may already exist from older Phoenix iterations.
-- CREATE TABLE IF NOT EXISTS does not add missing columns, so keep these
-- additive guards before indexes and API code depend on the columns.
alter table public.customers add column if not exists company_name text;
alter table public.customers add column if not exists organization_number text;
alter table public.customers add column if not exists email text;
alter table public.customers add column if not exists phone text;
alter table public.customers add column if not exists website text;
alter table public.customers add column if not exists address text;
alter table public.customers add column if not exists customer_type text;
alter table public.customers add column if not exists status text not null default 'lead';
alter table public.customers add column if not exists notes text;
alter table public.customers add column if not exists source text;
alter table public.customers add column if not exists created_at timestamptz not null default now();
alter table public.customers add column if not exists updated_at timestamptz not null default now();

alter table public.contacts add column if not exists customer_id uuid references public.customers(id) on delete cascade;
alter table public.contacts add column if not exists name text;
alter table public.contacts add column if not exists email text;
alter table public.contacts add column if not exists phone text;
alter table public.contacts add column if not exists role text;
alter table public.contacts add column if not exists is_primary boolean not null default false;
alter table public.contacts add column if not exists notes text;
alter table public.contacts add column if not exists created_at timestamptz not null default now();
alter table public.contacts add column if not exists updated_at timestamptz not null default now();

alter table public.leads add column if not exists customer_id uuid references public.customers(id) on delete set null;
alter table public.leads add column if not exists contact_id uuid references public.contacts(id) on delete set null;
alter table public.leads add column if not exists source_request_id uuid references public.requests(id) on delete set null;
alter table public.leads add column if not exists title text;
alter table public.leads add column if not exists description text;
alter table public.leads add column if not exists status text not null default 'open';
alter table public.leads add column if not exists value_estimate numeric(12,2);
alter table public.leads add column if not exists source text default 'requests';
alter table public.leads add column if not exists created_at timestamptz not null default now();
alter table public.leads add column if not exists updated_at timestamptz not null default now();

alter table public.quotes add column if not exists customer_id uuid references public.customers(id) on delete set null;
alter table public.quotes add column if not exists contact_id uuid references public.contacts(id) on delete set null;
alter table public.quotes add column if not exists lead_id uuid references public.leads(id) on delete set null;
alter table public.quotes add column if not exists source_request_id uuid references public.requests(id) on delete set null;
alter table public.quotes add column if not exists title text;
alter table public.quotes add column if not exists description text;
alter table public.quotes add column if not exists status text not null default 'kladd';
alter table public.quotes add column if not exists valid_until date;
alter table public.quotes add column if not exists total_ex_vat numeric(12,2) not null default 0;
alter table public.quotes add column if not exists total_vat numeric(12,2) not null default 0;
alter table public.quotes add column if not exists total_inc_vat numeric(12,2) not null default 0;
alter table public.quotes add column if not exists internal_notes text;
alter table public.quotes add column if not exists customer_note text;
alter table public.quotes add column if not exists created_at timestamptz not null default now();
alter table public.quotes add column if not exists updated_at timestamptz not null default now();

alter table public.quote_items add column if not exists quote_id uuid references public.quotes(id) on delete cascade;
alter table public.quote_items add column if not exists description text;
alter table public.quote_items add column if not exists quantity numeric(12,2) not null default 1;
alter table public.quote_items add column if not exists unit_price numeric(12,2) not null default 0;
alter table public.quote_items add column if not exists discount numeric(12,2) not null default 0;
alter table public.quote_items add column if not exists vat_rate numeric(5,2) not null default 25;
alter table public.quote_items add column if not exists line_total_ex_vat numeric(12,2) not null default 0;
alter table public.quote_items add column if not exists created_at timestamptz not null default now();

alter table public.quote_messages add column if not exists quote_id uuid;
alter table public.quote_messages add column if not exists author_id uuid;
alter table public.quote_messages add column if not exists author_name text;
alter table public.quote_messages add column if not exists author_type text default 'customer';
alter table public.quote_messages add column if not exists message text;
alter table public.quote_messages add column if not exists created_at timestamptz not null default now();

alter table public.quote_tokens add column if not exists quote_id uuid;
alter table public.quote_tokens add column if not exists token text;
alter table public.quote_tokens add column if not exists expires_at timestamptz;
alter table public.quote_tokens add column if not exists created_at timestamptz not null default now();

alter table public.quote_portal_tokens add column if not exists quote_id uuid;
alter table public.quote_portal_tokens add column if not exists token text;
alter table public.quote_portal_tokens add column if not exists expires_at timestamptz;
alter table public.quote_portal_tokens add column if not exists created_at timestamptz not null default now();

alter table public.phoenix_ideas add column if not exists title text;
alter table public.phoenix_ideas add column if not exists description text;
alter table public.phoenix_ideas add column if not exists category text;
alter table public.phoenix_ideas add column if not exists status text not null default 'parkert';
alter table public.phoenix_ideas add column if not exists created_at timestamptz not null default now();
alter table public.phoenix_ideas add column if not exists updated_at timestamptz not null default now();

alter table public.phoenix_site_content add column if not exists key text not null default 'homepage';
alter table public.phoenix_site_content add column if not exists title text;
alter table public.phoenix_site_content add column if not exists content jsonb;
alter table public.phoenix_site_content add column if not exists section text;
alter table public.phoenix_site_content add column if not exists page text default 'home';
alter table public.phoenix_site_content add column if not exists updated_at timestamptz not null default now();
alter table public.phoenix_site_content add column if not exists created_at timestamptz not null default now();

alter table public.requests add column if not exists customer_id uuid references public.customers(id) on delete set null;
alter table public.requests add column if not exists contact_id uuid references public.contacts(id) on delete set null;
alter table public.requests add column if not exists lead_id uuid references public.leads(id) on delete set null;
alter table public.requests add column if not exists converted_at timestamptz;
alter table public.requests add column if not exists converted_to_customer boolean not null default false;

create index if not exists idx_contacts_customer_id on public.contacts(customer_id);
create index if not exists idx_leads_customer_id on public.leads(customer_id);
create index if not exists idx_leads_source_request_id on public.leads(source_request_id);
create index if not exists idx_requests_customer_id on public.requests(customer_id);
create index if not exists idx_requests_lead_id on public.requests(lead_id);
create index if not exists idx_phoenix_ideas_status on public.phoenix_ideas(status);
create index if not exists idx_quotes_customer_id on public.quotes(customer_id);
create index if not exists idx_quotes_lead_id on public.quotes(lead_id);
create index if not exists idx_quote_items_quote_id on public.quote_items(quote_id);
create index if not exists idx_quote_messages_quote_id on public.quote_messages(quote_id);
create index if not exists idx_quote_tokens_token on public.quote_tokens(token);
create index if not exists idx_quote_portal_tokens_token on public.quote_portal_tokens(token);
create unique index if not exists idx_phoenix_site_content_key_page on public.phoenix_site_content(key, page);

alter table if exists public.quote_messages add column if not exists author_type text default 'customer';
alter table if exists public.quote_messages add column if not exists author_name text;
alter table if exists public.requests add column if not exists portal_status text;
