-- Quote portal tokens must point to real quotes, not legacy requests.

do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'quote_portal_tokens'
      and column_name = 'id'
  ) then
    alter table public.quote_portal_tokens
      add column id bigint generated by default as identity;
  end if;
end $$;

update public.quote_portal_tokens qpt
set quote_id = q.id
from public.quotes q
where q.source_request_id = qpt.quote_id
  and not exists (
    select 1
    from public.quotes direct_quote
    where direct_quote.id = qpt.quote_id
  );

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.quote_portal_tokens'::regclass
      and contype = 'p'
  ) then
    alter table public.quote_portal_tokens
      add constraint quote_portal_tokens_pkey primary key (id);
  end if;
end $$;

alter table public.quote_portal_tokens
  drop constraint if exists quote_portal_tokens_quote_id_fkey;

alter table public.quote_portal_tokens
  add constraint quote_portal_tokens_quote_id_fkey
  foreign key (quote_id) references public.quotes(id) on delete cascade;

create index if not exists idx_quote_portal_tokens_quote_id
  on public.quote_portal_tokens(quote_id);

create index if not exists idx_quote_portal_tokens_token_lookup
  on public.quote_portal_tokens(token);
